# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['audio_downloader/__main__.py'],
    pathex=[os.path.dirname(os.path.abspath(SPEC))],
    binaries=[],
    datas=[],
    collect_all=['selenium', 'webdriver_manager'],
    hiddenimports=[
        'audio_downloader.gui',
        'audio_downloader.config',
        'audio_downloader.browser_manager', 
        'audio_downloader.download_utils',
        'audio_downloader.sources',
        'audio_downloader.sources.base',
        'audio_downloader.sources.melinda_myers',
        'audio_downloader.sources.northwest_outdoors',
        'audio_downloader.sources.whittler',
        'audio_downloader.sources.clear_out_west',
        'audio_downloader.sources.weekend_in_the_country',
        'cryptography',
        'OpenSSL',
        'h2',
        'h2.events',
        'h2.connection',
        'wsaccel',
        'python_socks',
        'websocket',
        'selenium.webdriver.firefox.webdriver',
        'selenium.webdriver.firefox.service',
        'selenium.webdriver.firefox.options',
        'selenium.webdriver.firefox.firefox_binary',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common.exceptions',
        'webdriver_manager.firefox',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AudioDownloader',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
